# Generated by Django 4.2.29 on 2026-03-24 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_location', models.CharField(max_length=300)),
                ('start_lat', models.FloatField(default=0.0)),
                ('start_lng', models.FloatField(default=0.0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_mode', models.CharField(choices=[('cheapest', 'Cheapest (Walk/Bus)'), ('fastest', 'Fastest (Cab/Train)')], default='cheapest', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('attraction', 'Attraction'), ('food', 'Food & Drink'), ('accommodation', 'Accommodation'), ('study', 'Study-Friendly Spot'), ('transport', 'Transport Hub'), ('shopping', 'Shopping'), ('nature', 'Nature & Parks'), ('other', 'Other')], default='attraction', max_length=30)),
                ('estimated_duration', models.IntegerField(default=60, help_text='Estimated time to spend here (minutes)')),
                ('entry_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('visit_order', models.IntegerField(default=0)),
                ('is_study_friendly', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='trips.trip')),
            ],
            options={
                'ordering': ['visit_order'],
            },
        ),
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_order', models.TextField(default='[]')),
                ('total_distance_km', models.FloatField(default=0)),
                ('total_travel_time_min', models.IntegerField(default=0)),
                ('total_visit_time_min', models.IntegerField(default=0)),
                ('optimization_algorithm', models.CharField(default='nearest_neighbor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_route', to='trips.trip')),
            ],
        ),
    ]
